
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD2AcjRW0YNzDH6jyU-i7mGfaoJRBN0Yg',
    appId: '1:1080356224517:web:b4d088076cd505b51da66c',
    messagingSenderId: '1080356224517',
    projectId: 'family-finances-ds',
    authDomain: 'family-finances-ds.firebaseapp.com',
    storageBucket: 'family-finances-ds.firebasestorage.app',
    measurementId: 'G-N620J13V8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1DhB7ekiUH4V2RNaG_AZ7FNjNIWtWqIU',
    appId: '1:1080356224517:android:5772a326fa8097f61da66c',
    messagingSenderId: '1080356224517',
    projectId: 'family-finances-ds',
    storageBucket: 'family-finances-ds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT8Dmd8OXQpEkJWw34-lWSSKSkN6mvvvo',
    appId: '1:1080356224517:ios:bf5da6eea1644ed11da66c',
    messagingSenderId: '1080356224517',
    projectId: 'family-finances-ds',
    storageBucket: 'family-finances-ds.firebasestorage.app',
    iosBundleId: 'com.ds.familyfinances',
  );
}
